# PURL configuration for http://purl.bican.org/taxonomy/CCN201912132

idspace: CCN201912132
base_url: /taxonomy/CCN201912132

products:
- CCN201912132.json: https://raw.githubusercontent.com/AllenInstitute/MOp_taxonomies_ontology/main/marmosetM1_CCN201912132/updated_dendrogram_CCN201912132.json

term_browser: ols
example_terms:
- PCL_0011124

entries:

- exact: /CCN201912132.json
  replacement: https://github.com/AllenInstitute/MOp_taxonomies_ontology/blob/main/marmosetM1_CCN201912132/nomenclature_table_CCN201912132.csv
#  replacement: https://raw.githubusercontent.com/AllenInstitute/MOp_taxonomies_ontology/main/marmosetM1_CCN201912132/updated_dendrogram_CCN201912132.json

- prefix: /releases/
  replacement: https://raw.githubusercontent.com/obophenotype/provisional_cell_ontology/v
  tests:
    - from: /releases/2022-01-24/
      to: https://raw.githubusercontent.com/obophenotype/provisional_cell_ontology/v2022-01-24/

## generic fall-through, serve direct from github by default
- prefix: /
  replacement: https://raw.githubusercontent.com/AllenInstitute/MOp_taxonomies_ontology/main/marmosetM1_CCN201912132/